
import { Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/provider/redux/ReduxProvider";

const poppins = Poppins({ subsets:['devanagari'], weight: ["100" , "200" , "300" , "400" , "500" , "600" , "700" , "800" , "900"] });

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <ReduxProvider>
    <html lang="en">
      <body className={poppins.className}>
      
      {children}
     
      </body>
    </html>
    </ReduxProvider>
  );
}
